//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string EditUserDataView_Button_Apply_Text {
            get {
                return ResourceManager.GetString("EditUserDataView_Button_Apply_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string EditUserDataView_Button_Cancel_Text {
            get {
                return ResourceManager.GetString("EditUserDataView_Button_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string EditUserDataView_Field_BirthDate_Hint {
            get {
                return ResourceManager.GetString("EditUserDataView_Field_BirthDate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string EditUserDataView_Field_FirstName_Hint {
            get {
                return ResourceManager.GetString("EditUserDataView_Field_FirstName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string EditUserDataView_Field_Gender_Hint {
            get {
                return ResourceManager.GetString("EditUserDataView_Field_Gender_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string EditUserDataView_Field_LastName_Hint {
            get {
                return ResourceManager.GetString("EditUserDataView_Field_LastName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string EditUserDataView_Field_MiddleName_Hint {
            get {
                return ResourceManager.GetString("EditUserDataView_Field_MiddleName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Personal Info.
        /// </summary>
        public static string EditUserDataView_Header_Text {
            get {
                return ResourceManager.GetString("EditUserDataView_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NEW ACCOUNT.
        /// </summary>
        public static string LoginView_Button_CreateNewAccount_Text {
            get {
                return ResourceManager.GetString("LoginView_Button_CreateNewAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string LoginView_Button_SignIn_Text {
            get {
                return ResourceManager.GetString("LoginView_Button_SignIn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginView_Field_Password_Text {
            get {
                return ResourceManager.GetString("LoginView_Field_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginView_Field_Username_Text {
            get {
                return ResourceManager.GetString("LoginView_Field_Username_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginView_Header_Text {
            get {
                return ResourceManager.GetString("LoginView_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string RegisterView_Button_Cancel_Text {
            get {
                return ResourceManager.GetString("RegisterView_Button_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        public static string RegisterView_Button_Register_Text {
            get {
                return ResourceManager.GetString("RegisterView_Button_Register_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string RegisterView_Field_BirthDate_Hint {
            get {
                return ResourceManager.GetString("RegisterView_Field_BirthDate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string RegisterView_Field_ConfirmPassword_Hint {
            get {
                return ResourceManager.GetString("RegisterView_Field_ConfirmPassword_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string RegisterView_Field_FirstName_Hint {
            get {
                return ResourceManager.GetString("RegisterView_Field_FirstName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string RegisterView_Field_Gender_Hint {
            get {
                return ResourceManager.GetString("RegisterView_Field_Gender_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string RegisterView_Field_LastName_Hint {
            get {
                return ResourceManager.GetString("RegisterView_Field_LastName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string RegisterView_Field_MiddleName_Hint {
            get {
                return ResourceManager.GetString("RegisterView_Field_MiddleName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterView_Field_Password_Hint {
            get {
                return ResourceManager.GetString("RegisterView_Field_Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string RegisterView_Field_Username_Hint {
            get {
                return ResourceManager.GetString("RegisterView_Field_Username_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string RegisterView_Header_Text {
            get {
                return ResourceManager.GetString("RegisterView_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Authorization_Password_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Authorization_Password_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Authorization_Username_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Authorization_Username_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, the date doesn&apos;t look right..
        /// </summary>
        public static string Validation_Editing_BirthDate_Must_Be_Be_Valid_Age {
            get {
                return ResourceManager.GetString("Validation_Editing_BirthDate_Must_Be_Be_Valid_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Editing_FirstName_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Editing_FirstName_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Editing_LastName_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Editing_LastName_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, the date doesn&apos;t look right..
        /// </summary>
        public static string Validation_Registration_BirthDate_Must_Be_Be_Valid_Age {
            get {
                return ResourceManager.GetString("Validation_Registration_BirthDate_Must_Be_Be_Valid_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Registration_ConfirmPassword_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Registration_ConfirmPassword_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These passwords don&apos;t match. Try again?.
        /// </summary>
        public static string Validation_Registration_ConfirmPassword_Not_Match_Password {
            get {
                return ResourceManager.GetString("Validation_Registration_ConfirmPassword_Not_Match_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Registration_FirstName_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Registration_FirstName_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Registration_LastName_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Registration_LastName_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Registration_Password_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Registration_Password_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username is taken. Try another..
        /// </summary>
        public static string Validation_Registration_Username_Already_Taken {
            get {
                return ResourceManager.GetString("Validation_Registration_Username_Already_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Validation_Registration_Username_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Validation_Registration_Username_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use only letters (a-z), numbers, and periods..
        /// </summary>
        public static string Validation_Registration_Username_Contains_Invalid_Characters {
            get {
                return ResourceManager.GetString("Validation_Registration_Username_Contains_Invalid_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use between {MinLength} and {MaxLength} characters..
        /// </summary>
        public static string Validation_Registration_Username_Invalid_Length {
            get {
                return ResourceManager.GetString("Validation_Registration_Username_Invalid_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value of user role..
        /// </summary>
        public static string Validation_Registration_UserRole_Invalid_Value {
            get {
                return ResourceManager.GetString("Validation_Registration_UserRole_Invalid_Value", resourceCulture);
            }
        }
    }
}
