//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum age should be larger than minimum.
        ///Max: {0}.
        ///Min: {1}..
        /// </summary>
        public static string Exception_BirthDateValidator_Maximum_Age_Less_Than_Minimum_Age {
            get {
                return ResourceManager.GetString("Exception_BirthDateValidator_Maximum_Age_Less_Than_Minimum_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum age should be a positive number.
        ///Value: {0}..
        /// </summary>
        public static string Exception_BirthDateValidator_Maximum_Age_Non_Positive {
            get {
                return ResourceManager.GetString("Exception_BirthDateValidator_Maximum_Age_Non_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age should be a positive number.
        ///Value: {0}..
        /// </summary>
        public static string Exception_BirthDateValidator_Minimum_Age_Non_Positive {
            get {
                return ResourceManager.GetString("Exception_BirthDateValidator_Minimum_Age_Non_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call RemoveWatch method before AddWatch..
        /// </summary>
        public static string Exception_BusyWatcher_No_Matching_AddWatch {
            get {
                return ResourceManager.GetString("Exception_BusyWatcher_No_Matching_AddWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{PropertyName}&apos; is not a valid date of birth. It must be between {Min} and {Max}. You entered {PropertyValue}..
        /// </summary>
        public static string Validation_BirthDateValidator_Default_Message {
            get {
                return ResourceManager.GetString("Validation_BirthDateValidator_Default_Message", resourceCulture);
            }
        }
    }
}
