//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Authorization_Password_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Authorization_Password_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Authorization_Username_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Authorization_Username_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exists..
        /// </summary>
        public static string Authorization_Username_Not_Found {
            get {
                return ResourceManager.GetString("Authorization_Username_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string Authorization_Username_Or_Password_Invalid {
            get {
                return ResourceManager.GetString("Authorization_Username_Or_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, the date doesn&apos;t look right. Be sure to use your actual date of birth..
        /// </summary>
        public static string Registration_BirthDate_Must_Be_Be_Valid_Age {
            get {
                return ResourceManager.GetString("Registration_BirthDate_Must_Be_Be_Valid_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Registration_ConfirmPassword_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Registration_ConfirmPassword_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These passwords don&apos;t match. Try again?.
        /// </summary>
        public static string Registration_ConfirmPassword_Not_Match_Password {
            get {
                return ResourceManager.GetString("Registration_ConfirmPassword_Not_Match_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Registration_FirstName_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Registration_FirstName_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Registration_LastName_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Registration_LastName_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Registration_Password_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Registration_Password_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username is taken. Try another..
        /// </summary>
        public static string Registration_Username_Already_Taken {
            get {
                return ResourceManager.GetString("Registration_Username_Already_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t leave this empty..
        /// </summary>
        public static string Registration_Username_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Registration_Username_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use only letters (a-z), numbers, and periods..
        /// </summary>
        public static string Registration_Username_Contains_Invalid_Characters {
            get {
                return ResourceManager.GetString("Registration_Username_Contains_Invalid_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use between {0} and {1} characters..
        /// </summary>
        public static string Registration_Username_Invalid_Length {
            get {
                return ResourceManager.GetString("Registration_Username_Invalid_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value of user role..
        /// </summary>
        public static string Registration_UserRole_Invalid_Value {
            get {
                return ResourceManager.GetString("Registration_UserRole_Invalid_Value", resourceCulture);
            }
        }
    }
}
