//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma.BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exists..
        /// </summary>
        public static string Exception_Authorization_Username_Not_Found {
            get {
                return ResourceManager.GetString("Exception_Authorization_Username_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string Exception_Authorization_Username_Or_Password_Invalid {
            get {
                return ResourceManager.GetString("Exception_Authorization_Username_Or_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} contains invalid hash..
        /// </summary>
        public static string Exception_Hash_Algorithm_Hash_Not_Specified {
            get {
                return ResourceManager.GetString("Exception_Hash_Algorithm_Hash_Not_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of iterations cannot be less than 1..
        /// </summary>
        public static string Exception_Hash_Algorithm_Iterations_Is_Less_Than_One {
            get {
                return ResourceManager.GetString("Exception_Hash_Algorithm_Iterations_Is_Less_Than_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash should contain iterations..
        /// </summary>
        public static string Exception_Hash_Algorithm_Iterations_Not_Specified {
            get {
                return ResourceManager.GetString("Exception_Hash_Algorithm_Iterations_Not_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} contains invalid salt..
        /// </summary>
        public static string Exception_Hash_Algorithm_Salt_Not_Specified {
            get {
                return ResourceManager.GetString("Exception_Hash_Algorithm_Salt_Not_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must match the next format: &apos;iterations:salt:hash&apos;..
        /// </summary>
        public static string Exception_Hash_Has_Wrong_Format {
            get {
                return ResourceManager.GetString("Exception_Hash_Has_Wrong_Format", resourceCulture);
            }
        }
    }
}
